In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("E:\Projects\Supply Chain\Datasets\smart_logistics_dataset.csv")
print(df.shape)
df.head(20)

(1000, 16)

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\laviv\AppData\Local\Temp\ipykernel_20396\3150997953.py:1: SyntaxWarning: invalid escape sequence '\P'
  df=pd.read_csv("E:\Projects\Supply Chain\Datasets\smart_logistics_dataset.csv")

,Timestamp,Asset_ID,Latitude,Longitude,Inventory_Level,Shipment_Status,Temperature,Humidity,Traffic_Status,Waiting_Time,User_Transaction_Amount,User_Purchase_Frequency,Logistics_Delay_Reason,Asset_Utilization,Demand_Forecast,Logistics_Delay
0,2024-03-20 00:11:14,Truck_7,-65.7383,11.2497,390,Delayed,27.0,67.8,Detour,38,320,4,NaN,60.1,285,1
1,2024-10-30 07:53:51,Truck_6,22.2748,-131.7086,491,In Transit,22.5,54.3,Heavy,16,439,7,Weather,80.9,174,1
2,2024-07-29 18:42:48,Truck_10,54.9232,79.5455,190,In Transit,25.2,62.2,Detour,34,355,3,NaN,99.2,260,0
3,2024-10-28 00:50:54,Truck_9,42.3900,-1.4788,330,Delivered,25.4,52.3,Heavy,37,227,5,Traffic,97.4,160,1
4,2024-09-27 15:52:58,Truck_7,-65.8477,47.9468,480,Delayed,20.5,57.2,Clear,56,197,6,NaN,71.6,270,1
5,2024-09-17 06:02:15,Truck_7,73.3312,46.5831,118,In Transit,24.3,61.8,Clear,56,258,10,NaN,66.8,189,0
6,2024-02-05 08:38:56,Truck_4,27.9307,147.5317,480,Delayed,20.7,75.4,Clear,32,263,3,NaN,73.3,198,1
7,2024-09-28 09:08:23,Truck_9,46.5643,-126.5348,222,In Transit,23.3,64.2,Detour,30,459,9,Traffic,73.8,253,0
8,2024-01-18 08:27:04,Truck_9,-83.6737,-31.7125,245,Delivered,26.4,77.2,Clear,14,183,2,NaN,69.6,206,0
9,2024-11-09 00:48:26,Truck_2,54.1683,-135.2676,389,In Transit,21.9,57.3,Clear,52,127,7,Mechanical Failure,63.1,224,0
10,2024-01-09 23:19:43,Truck_9,82.9633,-154.5274,319,Delayed,22.0,53.5,Clear,28,360,4,NaN,69.8,171,1
11,2024-02-02 22:28:16,Truck_10,-25.2768,156.1262,234,Delivered,29.7,63.6,Detour,13,406,10,Traffic,85.5,238,0
12,2024-02-17 21:14:42,Truck_8,-65.5260,-3.0202,154,In Transit,21.5,74.2,Detour,38,215,3,Weather,84.4,114,0
13,2024-03-04 06:44:50,Truck_2,-26.1836,-30.3641,348,Delivered,27.3,71.6,Detour,30,211,2,NaN,96.4,115,0
14,2024-08-28 12:19:14,Truck_3,2.6709,-80.8879,163,In Transit,25.1,76.8,Heavy,54,320,5,Weather,93.2,231,1
15,2024-01-04 22:52:43,Truck_5,-22.4793,-54.5143,130,Delayed,23.7,68.1,Clear,45,487,4,Traffic,84.1,256,1
16,2024-10-30 17:52:03,Truck_4,-34.5353,-40.8617,391,Delayed,21.6,72.5,Clear,58,298,7,Traffic,61.5,170,1
17,2024-07-15 15:42:02,Truck_7,-8.7105,-17.8347,344,Delayed,21.4,53.5,Detour,23,461,9,NaN,93.4,106,1
18,2024-01-19 06:42:30,Truck_5,14.6629,116.0696,409,Delayed,27.5,66.6,Detour,29,492,3,NaN,72.6,204,1
19,2024-04-28 21:23:34,Truck_10,75.7743,108.9425,457,In Transit,25.5,75.9,Clear,21,315,3,Traffic,83.4,248,0

In [3]:
df=df.drop(['Inventory_Level','Asset_ID','User_Transaction_Amount','User_Purchase_Frequency','Asset_Utilization'],axis=1)
df.head(10)

,Timestamp,Latitude,Longitude,Shipment_Status,Temperature,Humidity,Traffic_Status,Waiting_Time,Logistics_Delay_Reason,Demand_Forecast,Logistics_Delay
0,2024-03-20 00:11:14,-65.7383,11.2497,Delayed,27.0,67.8,Detour,38,NaN,285,1
1,2024-10-30 07:53:51,22.2748,-131.7086,In Transit,22.5,54.3,Heavy,16,Weather,174,1
2,2024-07-29 18:42:48,54.9232,79.5455,In Transit,25.2,62.2,Detour,34,NaN,260,0
3,2024-10-28 00:50:54,42.3900,-1.4788,Delivered,25.4,52.3,Heavy,37,Traffic,160,1
4,2024-09-27 15:52:58,-65.8477,47.9468,Delayed,20.5,57.2,Clear,56,NaN,270,1
5,2024-09-17 06:02:15,73.3312,46.5831,In Transit,24.3,61.8,Clear,56,NaN,189,0
6,2024-02-05 08:38:56,27.9307,147.5317,Delayed,20.7,75.4,Clear,32,NaN,198,1
7,2024-09-28 09:08:23,46.5643,-126.5348,In Transit,23.3,64.2,Detour,30,Traffic,253,0
8,2024-01-18 08:27:04,-83.6737,-31.7125,Delivered,26.4,77.2,Clear,14,NaN,206,0
9,2024-11-09 00:48:26,54.1683,-135.2676,In Transit,21.9,57.3,Clear,52,Mechanical Failure,224,0

In [4]:
df["Timestamp"] = pd.to_datetime(df["Timestamp"])

df["hour"] = df["Timestamp"].dt.hour
df["day"] = df["Timestamp"].dt.day
df["dayofweek"] = df["Timestamp"].dt.dayofweek
df["is_weekend"] = df["dayofweek"].isin([5, 6]).astype(int)
df=df.drop('Timestamp',axis=1)
df

,Latitude,Longitude,Shipment_Status,Temperature,Humidity,Traffic_Status,Waiting_Time,Logistics_Delay_Reason,Demand_Forecast,Logistics_Delay,hour,day,dayofweek,is_weekend
0,-65.7383,11.2497,Delayed,27.0,67.8,Detour,38,NaN,285,1,0,20,2,0
1,22.2748,-131.7086,In Transit,22.5,54.3,Heavy,16,Weather,174,1,7,30,2,0
2,54.9232,79.5455,In Transit,25.2,62.2,Detour,34,NaN,260,0,18,29,0,0
3,42.3900,-1.4788,Delivered,25.4,52.3,Heavy,37,Traffic,160,1,0,28,0,0
4,-65.8477,47.9468,Delayed,20.5,57.2,Clear,56,NaN,270,1,15,27,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,89.8701,73.6867,Delivered,26.9,70.0,Heavy,32,Weather,213,1,16,22,0,0
996,-10.4792,-177.1239,Delivered,23.7,77.9,Detour,56,Weather,272,0,4,30,1,0
997,-71.0609,75.3714,In Transit,21.0,63.1,Detour,35,NaN,275,0,22,27,6,1
998,-76.7910,18.3631,Delivered,18.0,64.3,Heavy,10,NaN,242,1,23,18,3,0
999,59.8356,-114.4198,Delayed,18.7,73.6,Clear,55,Mechanical Failure,141,1,19,18,2,0

In [5]:
categorical_cols = ["Traffic_Status", "Shipment_Status"]
df_encoded = pd.get_dummies(df, columns=categorical_cols, drop_first=True)

X = df_encoded.drop(columns=["Logistics_Delay", "Logistics_Delay_Reason"],errors="ignore")
y = df_encoded["Logistics_Delay"]

df_encoded

,Latitude,Longitude,Temperature,Humidity,Waiting_Time,Logistics_Delay_Reason,Demand_Forecast,Logistics_Delay,hour,day,dayofweek,is_weekend,Traffic_Status_Detour,Traffic_Status_Heavy,Shipment_Status_Delivered,Shipment_Status_In Transit
0,-65.7383,11.2497,27.0,67.8,38,NaN,285,1,0,20,2,0,True,False,False,False
1,22.2748,-131.7086,22.5,54.3,16,Weather,174,1,7,30,2,0,False,True,False,True
2,54.9232,79.5455,25.2,62.2,34,NaN,260,0,18,29,0,0,True,False,False,True
3,42.3900,-1.4788,25.4,52.3,37,Traffic,160,1,0,28,0,0,False,True,True,False
4,-65.8477,47.9468,20.5,57.2,56,NaN,270,1,15,27,4,0,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,89.8701,73.6867,26.9,70.0,32,Weather,213,1,16,22,0,0,False,True,True,False
996,-10.4792,-177.1239,23.7,77.9,56,Weather,272,0,4,30,1,0,True,False,True,False
997,-71.0609,75.3714,21.0,63.1,35,NaN,275,0,22,27,6,1,True,False,False,True
998,-76.7910,18.3631,18.0,64.3,10,NaN,242,1,23,18,3,0,False,True,True,False
999,59.8356,-114.4198,18.7,73.6,55,Mechanical Failure,141,1,19,18,2,0,False,False,False,False

In [6]:
correlations = X.corrwith(y).sort_values(ascending=False)
correlations

Traffic_Status_Heavy          0.610384
Latitude                      0.039634
hour                          0.020766
Longitude                     0.011796
is_weekend                    0.004004
day                          -0.000025
Humidity                     -0.000504
dayofweek                    -0.009341
Demand_Forecast              -0.018621
Temperature                  -0.038067
Waiting_Time                 -0.063036
Traffic_Status_Detour        -0.302499
Shipment_Status_Delivered    -0.312688
Shipment_Status_In Transit   -0.342258
dtype: float64

In [7]:
X = X.drop(columns=[c for c in X.columns if c.startswith("Shipment_Status")])
X

,Latitude,Longitude,Temperature,Humidity,Waiting_Time,Demand_Forecast,hour,day,dayofweek,is_weekend,Traffic_Status_Detour,Traffic_Status_Heavy
0,-65.7383,11.2497,27.0,67.8,38,285,0,20,2,0,True,False
1,22.2748,-131.7086,22.5,54.3,16,174,7,30,2,0,False,True
2,54.9232,79.5455,25.2,62.2,34,260,18,29,0,0,True,False
3,42.3900,-1.4788,25.4,52.3,37,160,0,28,0,0,False,True
4,-65.8477,47.9468,20.5,57.2,56,270,15,27,4,0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
995,89.8701,73.6867,26.9,70.0,32,213,16,22,0,0,False,True
996,-10.4792,-177.1239,23.7,77.9,56,272,4,30,1,0,True,False
997,-71.0609,75.3714,21.0,63.1,35,275,22,27,6,1,True,False
998,-76.7910,18.3631,18.0,64.3,10,242,23,18,3,0,False,True
999,59.8356,-114.4198,18.7,73.6,55,141,19,18,2,0,False,False

In [8]:
X["congestion_index"] = (
    X["Traffic_Status_Heavy"] * 1.0 +
    X["Traffic_Status_Detour"] * 0.7 +
    (X["Waiting_Time"] / X["Waiting_Time"].max()) * 0.5 +
    (X["Demand_Forecast"] / X["Demand_Forecast"].max()) * 0.3
)
X

,Latitude,Longitude,Temperature,Humidity,Waiting_Time,Demand_Forecast,hour,day,dayofweek,is_weekend,Traffic_Status_Detour,Traffic_Status_Heavy,congestion_index
0,-65.7383,11.2497,27.0,67.8,38,285,0,20,2,0,True,False,1.301667
1,22.2748,-131.7086,22.5,54.3,16,174,7,30,2,0,False,True,1.307333
2,54.9232,79.5455,25.2,62.2,34,260,18,29,0,0,True,False,1.243333
3,42.3900,-1.4788,25.4,52.3,37,160,0,28,0,0,False,True,1.468333
4,-65.8477,47.9468,20.5,57.2,56,270,15,27,4,0,False,False,0.736667
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,89.8701,73.6867,26.9,70.0,32,213,16,22,0,0,False,True,1.479667
996,-10.4792,-177.1239,23.7,77.9,56,272,4,30,1,0,True,False,1.438667
997,-71.0609,75.3714,21.0,63.1,35,275,22,27,6,1,True,False,1.266667
998,-76.7910,18.3631,18.0,64.3,10,242,23,18,3,0,False,True,1.325333
999,59.8356,-114.4198,18.7,73.6,55,141,19,18,2,0,False,False,0.599333

In [9]:
X["is_peak_hour"] = X["hour"].isin([8,9,10,17,18,19]).astype(int)
X["peak_traffic_risk"] = X["is_peak_hour"] * (
    X["Traffic_Status_Heavy"] + X["Traffic_Status_Detour"]
)

X["lat_bin"] = (X["Latitude"] // 5).astype(int)
X["lon_bin"] = (X["Longitude"] // 5).astype(int)
X["geo_region"] = X["lat_bin"].astype(str) + "_" + X["lon_bin"].astype(str)
region_delay_rate = (
    pd.concat([X["geo_region"], y], axis=1)
    .groupby("geo_region")["Logistics_Delay"]
    .mean()
)

X["region_risk"] = X["geo_region"].map(region_delay_rate)
X["region_risk"].fillna(X["region_risk"].mean(), inplace=True)

X

C:\Users\laviv\AppData\Local\Temp\ipykernel_20396\3440124520.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X["region_risk"].fillna(X["region_risk"].mean(), inplace=True)

,Latitude,Longitude,Temperature,Humidity,Waiting_Time,Demand_Forecast,hour,day,dayofweek,is_weekend,Traffic_Status_Detour,Traffic_Status_Heavy,congestion_index,is_peak_hour,peak_traffic_risk,lat_bin,lon_bin,geo_region,region_risk
0,-65.7383,11.2497,27.0,67.8,38,285,0,20,2,0,True,False,1.301667,0,0,-14,2,-14_2,1.0
1,22.2748,-131.7086,22.5,54.3,16,174,7,30,2,0,False,True,1.307333,0,0,4,-27,4_-27,1.0
2,54.9232,79.5455,25.2,62.2,34,260,18,29,0,0,True,False,1.243333,1,1,10,15,10_15,0.0
3,42.3900,-1.4788,25.4,52.3,37,160,0,28,0,0,False,True,1.468333,0,0,8,-1,8_-1,1.0
4,-65.8477,47.9468,20.5,57.2,56,270,15,27,4,0,False,False,0.736667,0,0,-14,9,-14_9,0.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,89.8701,73.6867,26.9,70.0,32,213,16,22,0,0,False,True,1.479667,0,0,17,14,17_14,1.0
996,-10.4792,-177.1239,23.7,77.9,56,272,4,30,1,0,True,False,1.438667,0,0,-3,-36,-3_-36,0.5
997,-71.0609,75.3714,21.0,63.1,35,275,22,27,6,1,True,False,1.266667,0,0,-15,15,-15_15,0.5
998,-76.7910,18.3631,18.0,64.3,10,242,23,18,3,0,False,True,1.325333,0,0,-16,3,-16_3,1.0
999,59.8356,-114.4198,18.7,73.6,55,141,19,18,2,0,False,False,0.599333,1,0,11,-23,11_-23,1.0

In [10]:
X["weather_stress"] = (
    (X["Temperature"] - X["Temperature"].mean()).abs() +
    (X["Humidity"] - X["Humidity"].mean()).abs()
)

hourly_demand = X.groupby("hour")["Demand_Forecast"].transform("mean")
X["relative_demand_pressure"] = X["Demand_Forecast"] / hourly_demand

X["delay_pressure"] = (
    X["Waiting_Time"] *
    (1 + X["Traffic_Status_Heavy"] + X["Traffic_Status_Detour"])
)

X = X.drop(columns=["lat_bin", "lon_bin", "geo_region"])

In [11]:
correlations = X.corrwith(y).sort_values(ascending=False)
correlations

region_risk                 0.908193
Traffic_Status_Heavy        0.610384
congestion_index            0.410736
delay_pressure              0.117777
peak_traffic_risk           0.079417
Latitude                    0.039634
hour                        0.020766
weather_stress              0.016694
Longitude                   0.011796
is_weekend                  0.004004
day                        -0.000025
Humidity                   -0.000504
is_peak_hour               -0.002539
dayofweek                  -0.009341
Demand_Forecast            -0.018621
relative_demand_pressure   -0.025409
Temperature                -0.038067
Waiting_Time               -0.063036
Traffic_Status_Detour      -0.302499
dtype: float64

In [12]:
X=X.drop(columns=["region_risk"])
X

,Latitude,Longitude,Temperature,Humidity,Waiting_Time,Demand_Forecast,hour,day,dayofweek,is_weekend,Traffic_Status_Detour,Traffic_Status_Heavy,congestion_index,is_peak_hour,peak_traffic_risk,weather_stress,relative_demand_pressure,delay_pressure
0,-65.7383,11.2497,27.0,67.8,38,285,0,20,2,0,True,False,1.301667,0,0,5.8639,1.469556,76
1,22.2748,-131.7086,22.5,54.3,16,174,7,30,2,0,False,True,1.307333,0,0,12.1361,0.898133,32
2,54.9232,79.5455,25.2,62.2,34,260,18,29,0,0,True,False,1.243333,1,1,4.1483,1.306831,68
3,42.3900,-1.4788,25.4,52.3,37,160,0,28,0,0,False,True,1.468333,0,0,14.2483,0.825014,74
4,-65.8477,47.9468,20.5,57.2,56,270,15,27,4,0,False,False,0.736667,0,0,11.2361,1.252900,56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,89.8701,73.6867,26.9,70.0,32,213,16,22,0,0,False,True,1.479667,0,0,7.9639,1.105919,64
996,-10.4792,-177.1239,23.7,77.9,56,272,4,30,1,0,True,False,1.438667,0,0,13.0517,1.369555,112
997,-71.0609,75.3714,21.0,63.1,35,275,22,27,6,1,True,False,1.266667,0,0,4.8361,1.384228,70
998,-76.7910,18.3631,18.0,64.3,10,242,23,18,3,0,False,True,1.325333,0,0,6.6361,1.170637,20
999,59.8356,-114.4198,18.7,73.6,55,141,19,18,2,0,False,False,0.599333,1,0,13.7517,0.746264,55

In [13]:
df_sorted = df.loc[X.index]

X_sorted = X.loc[df_sorted.index]
y_sorted = y.loc[df_sorted.index]

split_idx = int(0.8*len(X_sorted))

X_train = X_sorted.iloc[:split_idx]
X_test  = X_sorted.iloc[split_idx:]

y_train = y_sorted.iloc[:split_idx]
y_test  = y_sorted.iloc[split_idx:]

In [14]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

baseline = LogisticRegression(
    max_iter=1000,
    class_weight="balanced"
)

baseline.fit(X_train, y_train)

baseline_preds = baseline.predict(X_test)
print("BASELINE MODEL")
print(classification_report(y_test, baseline_preds))

BASELINE MODEL
              precision    recall  f1-score   support

           0       0.70      1.00      0.82        94
           1       1.00      0.61      0.76       106

    accuracy                           0.80       200
   macro avg       0.85      0.81      0.79       200
weighted avg       0.86      0.80      0.79       200

c:\Users\laviv\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [15]:
from xgboost import XGBClassifier

xgb_model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric="logloss",
    random_state=42
)

xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, feature_weights=None, gamma=None,
              grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=None,
              num_parallel_tree=None, ...)

In [16]:
xgb_preds = xgb_model.predict(X_test)

print("XGBOOST MODEL")
print(classification_report(y_test, xgb_preds))

XGBOOST MODEL
              precision    recall  f1-score   support

           0       0.72      0.78      0.74        94
           1       0.79      0.73      0.75       106

    accuracy                           0.75       200
   macro avg       0.75      0.75      0.75       200
weighted avg       0.75      0.75      0.75       200

In [17]:
y_probs = xgb_model.predict_proba(X_test)[:, 1]

from sklearn.metrics import precision_score, recall_score, f1_score

def evaluate_threshold(threshold):
    y_pred_thresh = (y_probs >= threshold).astype(int)
    return {
        "threshold": threshold,
        "precision": precision_score(y_test, y_pred_thresh),
        "recall": recall_score(y_test, y_pred_thresh),
        "f1": f1_score(y_test, y_pred_thresh)
    }

import pandas as pd

results = []
for t in [0.1, 0.2, 0.33, 0.4, 0.5]:
    results.append(evaluate_threshold(t))

pd.DataFrame(results)

   threshold  precision    recall        f1
0       0.10   0.561798  0.943396  0.704225
1       0.20   0.620000  0.877358  0.726562
2       0.33   0.691667  0.783019  0.734513
3       0.40   0.732143  0.773585  0.752294
4       0.50   0.785714  0.726415  0.754902

In [18]:
import lightgbm as lgb
from lightgbm import LGBMClassifier

lgb_model = LGBMClassifier(
    n_estimators=500,
    learning_rate=0.05,
    max_depth=-1,
    num_leaves=31,
    subsample=0.8,
    colsample_bytree=0.8,
    class_weight="balanced",
    random_state=42
)

lgb_model.fit(X_train, y_train)

[LightGBM] [Info] Number of positive: 460, number of negative: 340
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000171 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1982
[LightGBM] [Info] Number of data points in the train set: 800, number of used features: 18
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=-0.000000
[LightGBM] [Info] Start training from score -0.000000
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

LGBMClassifier(class_weight='balanced', colsample_bytree=0.8,
               learning_rate=0.05, n_estimators=500, random_state=42,
               subsample=0.8)

In [19]:
from sklearn.metrics import classification_report

lgb_preds = lgb_model.predict(X_test)

print("LIGHTGBM MODEL")
print(classification_report(y_test, lgb_preds))

LIGHTGBM MODEL
              precision    recall  f1-score   support

           0       0.71      0.77      0.74        94
           1       0.78      0.73      0.75       106

    accuracy                           0.74       200
   macro avg       0.75      0.75      0.74       200
weighted avg       0.75      0.74      0.75       200

In [20]:
import joblib

joblib.dump(xgb_model, "delay_model.pkl")

['delay_model.pkl']